apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
    # volumes we need access from database volume claim config
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
      - name: postgres
        image: postgres
        # resources:
        #   limits:
        #     memory: "128Mi" 
        #     cpu: "500m"
        ports:
        - containerPort: 5432
        #Need to add volume munt to the containers which are to be accesed with volumes with default name mount path, subpath
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
          # override default password
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: PGPASSWORD  